# main profile
spring:
  application:
    name: cumulative-materials
  profiles:
    active: dev


  jackson:
    parser:
      allow-numeric-leading-zeros: true
  http:
    converters:
      preferred-json-mapper: jackson
server.port: 8080


---
#########################################################
# dev profile
########################################################
spring.profiles: dev
spring.profiles.include:
  - h2
---
# h2database profile
spring:
  profiles: h2
  #   connection requestConfiguration for in memory database
  #   data source requestConfiguration
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cumulative-materials;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
  # JPA requestConfiguration
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop
  # H2 database requestConfiguration
  h2:
    console:
      enabled: true
      path: /console
#      settings:
#        web-allow-others: true
---
# mysql profile
spring:
  profiles: mySql
  # connection configuration for MySQL database
  # data source configuration
  datasource:
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql:0.0.0.0:3306/srtoybizSqlCumulateMaterials?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  # JPA configuration
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: none
#    hibernate.ddl-auto: create
#---

